### ISSUE TITLE
Main package: configuration and CLI

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli-extensions#1]
Responsible for parsing the configuration, starting the HTTP server and build processes.

- [x] Explore, decide on and document configuration file format
  Rolled up configuration format (a.k.a `Shopifile.yml`) is generated on the fly and passed from the Shopify CLI to `shopify-extensions` via STDIN.
- [x] Parse configuration information received via STDIN. This serves as a blueprint for a persisted universal configuration file in future. In the meantime the Ruby CLI will be responsible for sourcing the information from `.env` and `.shopify-cli.yml`. This is a replacement for today's command line flag based contract between the Ruby and Node process. Using a structure format such as YAML is much easier to extend than the former.
- [x] For every extension in the configuration file, create an API handler / ServeMux and build orchestrator and run them in their respective Go routines. Again, use Go's context package for cancellation management.
- [x] Start HTTP server and wait for user interrupt (CTRL-C). When interrupt occurs, cancel all contexts and shutdown.
- [x] Support reading configuration information from disk 
- [x] Compare `extension.config.yml` with the partial (not-nested version for a single extension) `Shopifile.yml` and discuss differences with Chris. There is likely no difference, but it's worth double checking. It's likely just a question of what file name to choose.

**Comment by vividviolet** [comment]
> This may totally just be a personal thing, but I hate the shortening dir with a hot passion. Many words start with dir and I feel like only people who are super command line-savvy have the instant association of dir => directory (lol I literally starting typing direction here because that is what I generally think of first).

I'm flexible with the naming for this but we need to make it clear what the field refers to. Do you think `root` and `out` is specific enough? What if we call it `rootDirectory` and `outDirectory`?

> What's your reasoning for nesting build and develop under development? To me that is a bit confusing (why is develop nested under development?), so I feel like they'd be nicer as top-level properties (or maybe just a differently-named parent key?)

I was thinking the nesting makes it clear that these configs are needed only for `serve/build` versus persisted in the DB. Currently everything nested under `development` will not be required in prod whereas `extensionPoints`, `metafields` and `name` should probably be persisted.

**Comment by t6d** [comment]
Closed in favour of #150, which tracks the remaining cleanup work.
