### ISSUE TITLE
Build package: build orchestration and file system watching

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli-extensions#2]
Responsible for running individual builds through `npm run build` and watching the `build/` directory for changes.

- [x] #15
- [x] create a util to parse the configuration file to extract build settings. This logic should live in its own NPM package so that it can also be consumed by partners that completely customize their build pipeline. **[JS]**
- [x] #20
- [x] Create a file system watcher for  `build/` directory that sends notifications either via callback or channel when a changes are registered **[Go]**
- [x] Include details about the build failure in the `Result` struct. This could simply be done by reading everything that was output to STDERR by esbuild and attaching to the result as an error by using `errors.New`: https://github.com/Shopify/shopify-cli-extensions/pull/45
    ```go
    type Result type {
      success bool
      error error
    }
    ```
- [x] Handle file system watching errors such as directory does not exist https://github.com/Shopify/shopify-cli-extensions/pull/45
- [x] ~Handle directory has been removed after watcher has started, build artifacts being deleted **[Go]**~ Decided not to address as this is an edge case that is not easy to solve. If it becomes a problem, we will address in the future.
- [ ] Graceful shutdown when interrupt occurs (CTRL-C) using Go's [`context`](https://pkg.go.dev/context) package **[Go]**
  - [x] Introduce `var main.ctx contex t.Context` and either initialize it in `main.main()` or `main.init()`. Pass a context from `main`, use `context.Background()` for now as we don't have any other information that needs to be attached to the context. https://github.com/Shopify/shopify-cli-extensions/pull/45
  - [x] In `main.Cli.build()` errors from the build process should be written to `os.Stderr` and lead to a non-zero exit code `os.Exit(1)`, but should not block the `build` of other extensions. https://github.com/Shopify/shopify-cli-extensions/pull/45
  - [x] In `main.Cli.serve()` errors from the process should be written to `os.Stderr` https://github.com/Shopify/shopify-cli-extensions/issues/72
  - [ ] #176
  - [x] #88
