### ISSUE TITLE
Deployment & Integration

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli-extensions#4]
Shopify CLI will be responsible for downloading the OS and CPU architecture appropriate binary of the `shopify-cli-extensions` binary from Github during installation.

## Fake deployment

- [x] Implement scrappy expermintal deploy workflow by updating the Makefile for `shopify-extensions` to have a task that builds and copies the binary to `/usr/local/bin`.

## Update `create`, `build`, `serve` to use `shopify-extensions`

- [x] Introduce a feature flag to guard workflows relying on the new `shopify-extensions` binary.
```
shopify config feature extension_server_beta --enable
```
- [x] Create an Operation (+ domain models) for building the configuration and serializing it to YAML. This should include global settings such as `port` and `tunnel-url`: https://github.com/Shopify/shopify-cli/pull/1481
    ```yaml
    extensions: ...
    apps: ...
    cli:
      port: 39...
      tunnel_url: https://1234.ngrok.io/
    ```
- [x] #76
- [x] #80
- [x] #89
- [x] #152
- [x] #92 
- [x] #91 

## Continuous deployment setup

- [x] Setup ShipIt for releasing the Node package and document the fact that the change set being deployed through ShipIt is likely substantially smaller than the number of PR displayed as most PRs will concern the Go code
- [x] Setup a GitHub Action that triggers on Release and cross-compiles the binaries and attaches them to the release
- [x] #206
- [ ] #208

## Automatically download `shopify-extensions`

- [x] Use Github releases and corresponding actions to cross-compile the Go code for all target OS and CPU architectures
- [x] #207
